### ISSUE TITLE
Intel SSSE3 error 

### ISSUE THREAD

**Issue by hardingnj** [conda-forge/numexpr-feedstock#3]
> numexpr                   2.6.1               np111py35_0    conda-forge

We are hitting an error trying to use numexpr installed via conda on different nodes in our compute cluster. On AMD64 nodes all is good but on Intel Xeon E5-2660 nodes we get the following error:

> [Thread debugging using libthread_db enabled]
> Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
> Core was generated by `/home/hidden/exec/miniconda3/envs/selection_alt/bin/python /home/hidden/git/xpclr/bin'.
> 
> Program terminated with signal 11, Segmentation fault.
> # 0  __memmove_ssse3_back () at ../sysdeps/x86_64/multiarch/memcpy-ssse3-back.S:1991
> 
> 1991    ../sysdeps/x86_64/multiarch/memcpy-ssse3-back.S: No such file or directory.
> (gdb) bt
> # 0  __memmove_ssse3_back () at ../sysdeps/x86_64/multiarch/memcpy-ssse3-back.S:1991
> # 1  0x00002afdf857098c in th_worker (tidptr=<optimised out>) at numexpr/module.cpp:92
> # 2  0x00002afdf3cfde9a in start_thread (arg=0x2afe4682e700) at pthread_create.c:308
> # 3  0x00002afdf491136d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:112
> # 4  0x0000000000000000 in ?? ()

We can work around this easily so please do not spend any time on this if it doesn't look like a quick fix, but thought I would report in case it's useful to know. Please feel free to close the issue if this is not a quick fix.

cc @hardingnj.

(C & P issue from: https://github.com/pydata/numexpr/issues/225)

via @alimanfoo

**Comment by scopatz** [comment]
Please reopen if this remains an issue.
